language: python
# Only python 27 is working for now
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"

before_install:
  - pip install "python-swiftclient>=2.0"

install:
  - pip install -M tox

script: tox
